# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiotracking', '0002_auto_20160918_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='day_string',
            field=models.CharField(default='', max_length=30),
        ),
    ]
