# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiotracking', '0003_program_day_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='channel',
            new_name='station',
        ),
    ]
