# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiotracking', '0004_auto_20161004_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('url', models.URLField(max_length=300)),
                ('band', models.CharField(choices=[('AM', 'AM'), ('FM', 'FM'), ('NA', 'None')], default='NA', max_length=2)),
                ('freq', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
