# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiotracking', '0005_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='url',
            new_name='website',
        ),
        migrations.AddField(
            model_name='station',
            name='stream_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
